#!/bin/bash

# Run only the bootloader in QEMU

if [ $1 ]
then
    PROFILE=${1:2:7}
else
    PROFILE="debug"
fi

qemu-system-x86_64 -serial stdio -hda target/x86_64-bean_os_bootloader/$PROFILE/bootloader.bin
