#!/bin/bash

# Start GDB with the profile-matching symbol file

if [ $1 ]
then
    PROFILE=${1:2:7}
else
    PROFILE="debug"
fi

# pipe QEMU output (stdout and stderr) to null
qemu-system-x86_64 -s -S -hda target/x86_64-bean_os_bootloader/$PROFILE/bootloader.bin &> /dev/null &

# start GDB and load the appropriate symbol file (generated during build)
gdb --symbols=target/x86_64-bean_os_bootloader/$PROFILE/bootloader.sym
